name: Publish reports

on:
  workflow_run:
    workflows:
      - 'Java CI with Gradle'
      types:
        - completed

jobs:
  publish:
    name: Publish Test Report
    runs-on: ubuntu-latest
    steps:
      - uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/**/TEST-*.xml'